In [2]:
# ipynb- Interactive Python Notebook
#py-python

In [3]:
#python programming

In [5]:
#hello
print('hello')

hello


In [6]:
#sequences in python
#sequences are containers , where certain elements could be stored
#Lists,Tuples,sets,Dictonary

In [7]:
#LIST -ordered , mutable ,aloow duplicants
a=[1,2,3,4,5,6,7,7,0]
print(a)

[1, 2, 3, 4, 5, 6, 7, 7, 0]


In [8]:
type(a) #variable a is alist

list

In [9]:
b=['mango',15,True,25.9]
b

['mango', 15, True, 25.9]

In [10]:
fruits=['mango','apple','grapes']
fruits

['mango', 'apple', 'grapes']

In [13]:
#operations on lists
fruits.append('banana')
#it will add a new element in the list  based on order

In [14]:
fruits

['mango', 'apple', 'grapes', 'banana', 'banana']

In [22]:
fruits.insert(2,'orange') #it will add anew element based on index

In [23]:
fruits

['mango', 'apple', 'orange', 'grapes', 'banana', 'banana']

In [24]:
fruits.remove('orange')
#removing the name based on element name

In [25]:
fruits

['mango', 'apple', 'grapes', 'banana', 'banana']

In [26]:
fruits.pop(4)
fruits

['mango', 'apple', 'grapes', 'banana']

In [27]:
fruits.reverse()

In [28]:
fruits

['banana', 'grapes', 'apple', 'mango']

In [30]:
#i want to acces the 1st element in fruits list [index=0]
fruits[0]

'banana'

In [31]:
fruits[3]

'mango'

In [32]:
fruits[-1]

'mango'

In [33]:
#now i want tomacces 1st 3 elements
fruits[0:3]

['banana', 'grapes', 'apple']

In [34]:
#operations on list
#.append-add new elemnt
#.insert-add a new element based on index
#.remove-remove an element
#.pop-remove any element based on index
#.reverse-reverse the order of the sit

In [35]:
#TUPle-() -ordered ,Immutable
#faster and effective than tupule
#due to immutability they are not preferred

In [36]:
a=(1,2,3,45,56,6,7)
a
type(a)

tuple

In [37]:
b=('mango',True,23.6,35)

In [38]:
#set-{}-unorederd
a={1,2,3,4,5,6,7,8,9,10}
a

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [39]:
type(a)

set

In [40]:
b={5,6,7,8,9,10,11,12,13,14}
b

{5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

In [43]:
#union of sets
a|b

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

In [44]:
#intersection of sets
a&b

{5, 6, 7, 8, 9, 10}

In [45]:
#Dictonary-{' ': ,' ': ,' ': }

In [46]:
data={1:'python',2:'java',3:'c++'}
data

{1: 'python', 2: 'java', 3: 'c++'}

In [47]:
#PYTHON LIBRARIES
#NUMPY
#PANDAS
#MATPLOTLIB
#SKLEARN
#OPENCV

In [48]:
#NUMPY-Numerical python
#it is used instead of a list-to store data
#NUMPY is faster and more efficient when compared to alist

In [49]:
import numpy as np

In [50]:
a=np.array(1)
a

array(1)

In [52]:
a.shape

()

In [53]:
a.ndim

0

In [54]:
a.size

1

In [55]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [57]:
b.shape #(6,)=(6,1) -5 columns and 1 row

(6,)

In [58]:
b.ndim

1

In [59]:
b.size

6

In [61]:
 c=np.array([[1,2,3],[4,5,6]])
 c

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
c.shape

(2, 3)

In [63]:
c.size

6

In [65]:
c.ndim

2

In [73]:
d=np.random.randint(0,10,10)

In [74]:
d

array([7, 6, 8, 8, 1, 6, 7, 7, 8, 1])

In [72]:
np.random.seed(0)
d=np.random.randint(0,10,10)
d

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [76]:
d.size

10

In [77]:
d.shape

(10,)

In [78]:
d.ndim

1

In [80]:
d.reshape(5,2)

array([[7, 6],
       [8, 8],
       [1, 6],
       [7, 7],
       [8, 1]])

In [82]:
d=d.reshape(2,5)

In [83]:
d

array([[7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])