In [ ]:
#LOGISTIC REGRESSSION- CLASSIFICATION TECHNIQUE (SUPERVISED LEARNING)
#IT CLASSIFIES OUR DATA(0 OR 1,PURCHASED OR NOT PURCHASED ,TRUE OR FALSE,MALE OR FEMALE,1 OR 2 OR 3)
#FOR CONTINEOUS DATA - APPLY REGRESSION TECHNIQUE
#FOR DESCRETE DATA -APPLY CLASSIFICATION

In [ ]:
#Dataset -SOCIAL NETWORK ADs
#dataset_url--https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/Social_Network_Ads.csv

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#STEP 1- TAKE THE DATA AND CRAETE DATAFRAME
df=pd.read_csv('https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df.shape #400 rows and 5 columns

(400, 5)

In [ ]:
df.size #total  no elements in df

2000

In [ ]:
df.info()  #gives us the info about the data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [ ]:
#purchased column have 0 and 1
#0 - Not purchased
#1 - purchased
#input -age and estimated salary
#output is purchased column

In [ ]:
#i want know the excat count of how many have purchased and how many not percagsed
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [ ]:
#step 4 -- is devide the data into input and output
#input should be always 2d
x= df.iloc[:,2:4].values
x

In [ ]:
x.ndim

2

In [ ]:
y=df.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
#step 5 train and test variables - here we use train test split module
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)
#variables name can change but their irder should not change
#when ever we consider tarin test split we have to consider 4 variables
#by default 75% of x and y goes to traning variables
#and rest 25% goes to testing variables
#random_state = 0 ,it is used to keep the variables constant training and testing variables constant

In [ ]:
print(x.shape) #(400,2) 100% of x
print(x_train.shape)  #(300,2) 75% of x
print(x_test.shape)  #(100,2)  25% of x

(400, 2)
(300, 2)
(100, 2)


In [ ]:
print(y.shape) #(400,1) 100% of y
print(y_train.shape)  #(300,1)  75% of y
print(y_test.shape)   #(100,1) 25% of y

(400,)
(300,)
(100,)


In [ ]:
#step 6 normalization or scaling(done only for inputs)
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [ ]:
#step 7 run a classifier or a regresser or clusterer
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [ ]:
#8 fit the model (maping or plotting of values in libraray)
model.fit(x_train,y_train) #we are creating our model using thr training variables

LogisticRegression()

In [ ]:
#step 9 - predict the output or predictor variable
y_pred=model.predict(x_test) # we will predict the output using input testing value

In [ ]:
y_pred # preditted output values

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y_test #actual input

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [ ]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

89.0

In [ ]:
#individual prediction
a=scaler.transform([[25,50000]])
a

array([[2.5e+01, 5.0e+04]])

In [ ]:
model.predict(a)

array([1])

In [ ]:
b=scaler.transform([[20,25000]])
b

array([[2.0e+01, 2.5e+04]])

In [ ]:
model.predict(b)

array([1])

In [ ]:
c=scaler.transform([[50,20000]])
c

array([[   50., 20000.]])

In [ ]:
model.predict(c)

array([1])

In [ ]:
d=scaler.transform([[25,70000]])
d

array([[2.5e+01, 7.0e+04]])

In [ ]:
model.predict(d)

array([1])